### ISSUE TITLE
Request for requirements.txt

### ISSUE THREAD

**Issue by JAEarly** [drivendataorg/sfp-cervical-biopsy-runtime#16]
Please could a requirements.txt file be added please to provide a list of valid packages.
I'm using virtualenv instead of conda; I assume it'll be find for the submission.

**Comment by pjbull** [comment]
We won't add one to the repo in order to avoid confusion. We want it to be explicit in only one place where and how dependencies will be installed.

Since the names of packages and versions don't easily match between `pip`/`conda` it would be a headache to maintain as people add dependencies.

If you absolutely can't use conda as your package manager for local development, here's a script that can approximate the conda environment with pip. Just to be clear, this script and the environment that is generated is not a supported way of generating the runtime environment. Just providing here to make things easy for you. We won't be updating or maintaining this script or anything like it.

```python
from pathlib import Path
import yaml

data = yaml.load(Path("runtime/py-cpu.yml").read_text())

# skip (packages that are only conda)
skips = [
    'openh264',
    'py-opencv',
    'python',
    'py-xgboost',
]

# replace (packages with different names or versions in pip/conda)
replacements = {
    "pytorch==1.6.0": "torch==1.6.0",
    "opencv==4.4.0": "opencv-python==4.4.0.44",
}

reqs = []

for c_req in data['dependencies']:
    if isinstance(c_req, dict):
        reqs += c_req['pip']
        continue
    else:
        package, conda_version = c_req.split('=')[:2]
        pip_spec = f"{package}=={conda_version}"

        if pip_spec in replacements:
            pip_spec = replacements[pip_spec]

        elif package in skips:
            continue

        reqs.append(pip_spec)


Path('requirements.txt').write_text("\n".join(reqs))
```

Here's the output:
```
fastai==2.0.13
lightgbm==2.3.1
mahotas==1.4.11
opencv-python==4.4.0.44
pandas==1.1.1
pillow==7.2.0
pip==20.2.2
python-dotenv==0.14.0
torch==1.6.0
scikit-image==0.17.2
scikit-learn==0.23.2
scipy==1.5.2
shapely==1.7.1
tensorflow==2.2.0
torchvision==0.7.0
xgboost==1.2.0
pyvips==2.1.12
openslide-python==1.1.2
imagecodecs==2020.5.30
```
